pool: 'default'

variables:
  node.version: '20.x'
  projectRoot: '.'

jobs:
  - job: deploy
    steps:
      - task: NodeTool@0
        displayName: 'Use Node.js $(node.version)'
        inputs:
          versionSpec: '$(node.version)'

      - script: |
          npm install
        workingDirectory: $(projectRoot)
        displayName: "Install dependencies"
      
      - task: ArchiveFiles@2
        displayName: 'Archive files'
        inputs:
          rootFolderOrFile: '$(projectRoot)'
          includeRootFolder: false
          archiveType: zip
          archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
          replaceExistingArchive: true
      
      - task: AzureWebApp@1
        displayName: 'Deploy Azure Web App'
        inputs:
          azureSubscription: 'x-force-service-connection'
          appType: 'webAppLinux'
          appName: "atc-2024-x-force-be-linux-web-app"
          package: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
          startUpCommand: 'npm run start:prod'
